### ISSUE TITLE
Remove disabled entities

### ISSUE THREAD

**Issue by woobenjamin** [rianadon/opensprinkler-card#1]
Hi! Thank you for an amazing card.
I have an 8 station setup, but some of the stations are not setup, so I have disabled them in Home Assistant. However, when I click the 3 dots .. I still see them. Is it possible to remove them? Or at least have a switch to control if they should be displayed on not please? Thanks again ...

![image](https://user-images.githubusercontent.com/45885373/123138431-dea3c100-d409-11eb-89b2-e908d8b3ba7d.png)

**Comment by rianadon** [comment]
I'm trying to keep the feature set small so I'm reluctant to add a switch / link to toggle whether they're shown, but I've added an option to the config to hide them.

**Comment by woobenjamin** [comment]
@rianadon You rock. Thank oyu for the very quick response!
