### ISSUE TITLE
Weird quirk when an entity is disabled

### ISSUE THREAD

**Issue by woobenjamin** [rianadon/opensprinkler-card#10]
So, I think I've found them weirdest quirk. Since I only have 4 zones, but I have 8 relays, I wanted to disable the 4 that are unused. It's not about OpenSprinkler, but it's about HA. I just want to keep things clean. 

But as soon as one of the entities is disabled, the OS-card doesn't display anymore. In fact, if you go into a dashboard and edit the various cards, it's not even there! 

I thought it was user error. For me, 9/10x it is. So, I added another OS-card. At that point, OS-card complains that the device doesn't even exist. 

After a lot of trial and error, I figured out that when even one entity is disabled, OS-card goes bye-bye. Even when you re-enable the device only a HA restart will be recognized by the card.

**Comment by Indianb0y016** [comment]
I've been pulling my hair out trying to figure out why my card wasnt showing! I decided not to post an issue because I was afraid it would be something trivial but it looks like its not just me. Hopefully dev can get it sorted soon cause this card is pretty.

**Comment by rianadon** [comment]
That's really weird. It sounds like maybe there's some error being thrown inside the card. If you go to the Home Assistant logs or the browser console, are there any errors that look like they're from the card?

Also, if you could provide your config that would help greatly, as I don't see this quirk on my end.

**Comment by woobenjamin** [comment]
Didn't see anything in my logs. Definitely looked there first. Not at my computer for a while, but you have my config from before. Only difference is the change to extra_entities

**Comment by Indianb0y016** [comment]
Can confirm. Re-enabled all the disabled entities and the card appeared as normal. Disabled the rain delay entity and it disappeared. I ASSUME it is because the entities are hardcoded in the card and cant be nonexistent, else the card will bug out. Nothing in logs unfortunately.

**Comment by rianadon** [comment]
Ohhh. You are disabling entities as in this switch, correct? Turning this off breaks things, so hopefully we are having the same problem.

<img width="572" alt="image" src="https://user-images.githubusercontent.com/18223213/124256188-e0dbde80-dadf-11eb-859c-03f12c498fbc.png">

I didn't even know you could do that.

**Comment by woobenjamin** [comment]
> Ohhh. You are disabling entities as in this switch, correct? Turning this off breaks things, so hopefully we are having the same problem.
> 
> <img alt="image" width="572" src="https://user-images.githubusercontent.com/18223213/124256188-e0dbde80-dadf-11eb-859c-03f12c498fbc.png">
> 
> I didn't even know you could do that.

That's exactly it. 
eg. Take a quick look at this:
![image](https://user-images.githubusercontent.com/45885373/124314079-b103f980-db26-11eb-9e81-3c5390875556.png)

So, when I bought our house, the stations were already there, and I'm integrating with what I have. But since I have an "Unknown" station, I want to disable the 3 entities (using what you referred above).

**Comment by Indianb0y016** [comment]
Same situation here. I have 11 Zones in our house and OS only has a 16 zone option after 8 zones. This leaves me with 5 zones that are useless and unneeded. Despite being disabled in OS, they show up in HA, which is just an integration thing. Hence the card relying on the full integration config, any entity being disabled will break the card. While it is unfortunate, I can understand why it is the way it is. So Im not upset about it. The card is useful because it removes the need to create manual station entities that rely on an input boolean, which is more than acceptable in my opinion. Great card! I would highly suggest adding this info in the readme so other users arent confused over issues like this.

**Comment by rianadon** [comment]
Thank you both! It should be possible to make the card still load even if there are disabled entities. I'll look into it.

**Comment by rianadon** [comment]
Fixed in v1.9
