### ISSUE TITLE
OpenSprinkler Enable in extra_entities

### ISSUE THREAD

**Issue by vinnyfuria** [rianadon/opensprinkler-card#11]
When `switch.opensprinkler_enabled` is included in `extra_entities` it doesn't affect the entity status:

1. When `switch.opensprinkler_enabled` is on, clicking the "stop" icon results in a spinning icon and the entity not turning off
2. When `switch.opensprinkler_enabled` is off, the "play" icon is grayed out not clickable

I think ideally, when `switch` entity is included in `extra_entities` it would be nice for a toggle switch to be available or else having the icons correctly changing the state.

Thanks.

**Comment by rianadon** [comment]
Thanks for the find! That's a bug; the switch should be a toggle switch.

**Comment by vinnyfuria** [comment]
Excellent! Thank you.
