### ISSUE TITLE
No drop down available to choose device

### ISSUE THREAD

**Issue by terryhonn** [rianadon/opensprinkler-card#19]
I have multiple controllers, and when I add a new card, nothing happens when I click on "Required options". 

I don't mind editing/working with YAML, can you provide a way to locate the device ID for inserting manually, please?

**Comment by rianadon** [comment]
Something must have broke. The device selector is no longer appearing for me either.

To find the device ID manually, navigate to Settings -> Devices & Services -> Devices and find your OpenSprinkler device. The url will look something like `http://homeassistant:8123/config/devices/device/###` where `###` is the device id.

Then add to the YAML:
```
device: ###
```

**Comment by Z3R0XRS** [comment]
Could you elaborate on this?
Which YAML file at what location? 
I've installed the OScard using HACS and the same issue arrise for me. I can't select a device. I've found the device ID but i have no idea where to put it.

**Comment by rianadon** [comment]
When you edit the card, you should see a button in the lower left called "Show Code Editor" like in this screenshot:

<img width="1031" alt="image" src="https://user-images.githubusercontent.com/18223213/202590722-ef8e88a1-98b8-4a07-80c4-c4a0d438bc1a.png">

Click the button to switch to the code editor.
You'll need to type in `device: <put the id here>`. 

I've forgotten to push a fix for the issue. Hopefully this will no longer be a problem soon.
