### ISSUE TITLE
How to put card Title??

### ISSUE THREAD

**Issue by ravlar** [rianadon/opensprinkler-card#20]
Maybe it's very simple but I've been unable to ser card title as the rest of the cards I'm using. Now it's a bit confusing because all the rest have a title but the new opensprinkler card... ?

Thanks in advance.

**Comment by rianadon** [comment]
Hey @ravlar. Sorry about the confusion in the configuration.

<img width="358" alt="Example of the card" src="https://github.com/rianadon/opensprinkler-card/assets/18223213/8bebcbcc-9124-4bf5-92f8-4e704e59fa22">


The text you see here ("The Sprinklers") is the title. You can set it from the editor. The card's design is different from other Home Assistant cards in that the icon will always appear next to the title. This is to help line up the text when the stations that are running are shown below the title or you have other entities displayed below like so:

<img width="455" src="https://github.com/rianadon/opensprinkler-card/assets/18223213/ef1b84b1-0d8f-4bcd-80fe-f285183534a2" alt="Example of other entities" />
