### ISSUE TITLE
async_forward_entry_setup issue

### ISSUE THREAD

**Issue by n3xus1** [rianadon/opensprinkler-card#23]
Any help trying to sort out this issue

Detected code that calls async_forward_entry_setup for integration opensprinkler with title: OpenSprinkler and entry_id: d7d8e9da9d5db3ab84359e5b5d6c0d0b, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1

**Comment by rianadon** [comment]
Hi! This is actually an issue with the OpenSprinkler integration, not the card. However, I have good news for you. The integration was updated last week to fix this problem, so upgrading it will remove that message: https://github.com/vinteo/hass-opensprinkler/releases/tag/v1.3.5.
