### ISSUE TITLE
Feature request: remove the 3 dots showing history

### ISSUE THREAD

**Issue by woobenjamin** [rianadon/opensprinkler-card#8]
Not sure if this is a HA specific thing, but I'd love to have the 3 dots that shows the station history be a configurable boolean entry. 

Why? 
1. I fat finger it all the time!!! (OK, that's probably a personal issue of mine!! hehe)
2. My wife doesn't need to have more buttons to push that she needs to. It only leads to more questions (OK, this is probably another personal issue!!)

Thanks for your effort. People like you make the whole HA what it is!!

**Comment by rianadon** [comment]
Hahaha thank you. I did squish everything together past the point of being friendly to touchscreens. I shall handle that soon 😁

**Comment by rianadon** [comment]
Will be addressed in v1.7. Please reopen if you still need more spacing between entities or you are still hungry for more buttons.
